---
events:

  jsconf-budapest-2024:
    label: "JSConf Budapest 2024"
    dates:
      - ticket-name-contains: "*"
        date: "June 27-28, 2024"
    catering:
      - ticket-name-contains: "*"
        net-price: 128
    invoice:
      id-prefix: "JSCBP"
      logo-image: "JSCBP-szamlazzhu.png"
      comment: |
        The invoice includes mediated services.
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true
      currency: EUR
    email:
      replyToAddress: "team@jsconfbp.com"
      subject: "Your invoice for JSConf Budapest 2024"
      message: |
        Dear Attendee!

        Thank you for purchasing tickets for JSConf Budapest 2024.

        Please find our official invoice for the conference attached.
        In case you have an issue with the invoice, or you have a general question
        regarding the conference please write to: team@jsconfbp.com

        The JSConf Budapest team
    bank:
      name: "Wise, SWIFT/BIC: TRWIBEB1XXX"
      accountNumber: "BE46-9671-1672-7136"
    tito-signature-validator-env: TITO_TOKEN_JS



  integration-test-event-2022:
    label: "JSConf Budapest 2022"
    dates:
      - ticket-name-contains: "*"
        date: "September 24-25, 2022"
      - ticket-name-contains: "workshop"
        date: "September 23, 2022"
    catering:
      - ticket-name-contains: "workshop"
        net-price: 20
      - ticket-name-contains: "online"
        net-price: 0
      - ticket-name-contains: "*"
        net-price: 40
    invoice:
      id-prefix: "JSSCT"
      logo-image: "JSCBP-szamlazzhu.png"
      comment: |
        The invoice includes mediated services.
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: false
      currency: EUR
    email:
      reply-to-address: "nec@jsconfbp.com"
      subject: "Your invoice for Integration Test Event 2022"
      message: |
        Dear Attendee!
        Thank you for taking part in Reinforce AI Conference 2022.
        Please find attached our official invoice for the Reinforce AI conference.
        In case you have an issue with the invoice please reply to this e-mail.
        In case you have a general question regarding the conference please write to: hello@reinforceconf.com
        The Reinforce conference team
    bank:
      name: "Raiffeisen Bank, SWIFT: UBRTHUHB"
      account-number: "HU18-1201-0659-0160-2199-0020-0008"
    tito-signature-validator-env: TITO_TOKEN_TESTMODE
